# metadata will be set as Global variable in flask backend

metadata = {
    "PTT": {
        "start_time" : (10,35),
        "end_time": (15,50),
        "want": 100000,
        "left": 100000,
        "market_volume":0,
        "market_value":0,
        "market_vwap":0,
        "plan":[{'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 36)},
                {'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 37)},
                ],
        "my_volume":0,
        "my_value":0,
        "my_vwap":0
    }, 
    "BANPU": {
        "start_time" : (10,35),
        "end_time": (15,50),
        "want": 100000,
        "left": 100000,
        "market_volume":0,
        "market_value":0,
        "market_vwap":0,
        "plan":[{'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 36)},
                {'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 37)},],
        "my_volume":0,
        "my_value":0,
        "my_vwap":0
    },
    "SCC": {
        "start_time" : (10,35),
        "end_time": (15,50),
        "want": 100000,
        "left": 100000,
        "market_volume":0,
        "market_value":0,
        "market_vwap":0,
        "plan":[{'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 36)},
                {'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 37)},],
        "my_volume":0,
        "my_value":0,
        "my_vwap":0
    },
    "AOT": {
        "start_time" : (10,35),
        "end_time": (15,50),
        "want": 100000,
        "left": 100000,
        "market_volume":0,
        "market_value":0,
        "market_vwap":0,
        "plan":[{'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 36)},
                {'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 37)},],
        "my_volume":0,
        "my_value":0,
        "my_vwap":0
    },
    "CPALL": {
        "start_time" : (10,35),
        "end_time": (15,50),
        "want": 100000,
        "left": 100000,
        "market_volume":0,
        "market_value":0,
        "market_vwap":0,
        "plan":[{'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 36)},
                {'LO_VOLUME': 0,
                'MO_VOLUME': 100,
                'LO_PRICE': 33.75,
                'MO_PRICE': 34.0,
                'TIME': (10, 37)},],
        "my_volume":0,
        "my_value":0,
        "my_vwap":0
    },
}